"""empty message

Revision ID: d94cd848fd11
Revises: 3c1b81f14906
Create Date: 2021-05-14 23:30:08.463681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94cd848fd11'
down_revision = '3c1b81f14906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_unique_constraint(None, 'user', ['public_id'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'public_id')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
